stages:
  - build
  - deploy

before_script:
  - "echo off"
  - 'call "%VS140COMNTOOLS%\vsvars32.bat"'

build:
  stage: build
  script:
  - 'msbuild.exe "Test.sln"'

deploy to prd:
  stage: deploy
  script:
  - 'msbuild.exe "Test.sln"'
  - 'copy *.* c:\Test\'
 